common/models/VideoView.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%video_view}}".
 *
 * @property int $id
 * @property string $video_id
 * @property int|null $user_id
 * @property int|null $created_at
 *
 * @property User $user
 * @property Video $video
 */
class VideoView extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%video_view}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['video_id'], 'required'],
            [['user_id', 'created_at'], 'integer'],
            [['video_id'], 'string', 'max' => 16],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['video_id'], 'exist', 'skipOnError' => true, 'targetClass' => Video::className(), 'targetAttribute' => ['video_id' => 'video_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'video_id' => 'Video ID',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\UserQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[Video]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\VideoQuery
     */
    public function getVideo()
    {
        return $this->hasOne(Video::className(), ['video_id' => 'video_id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\VideoViewQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VideoViewQuery(get_called_class());
    }
}

backend/controllers/VideoController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Video;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * VideoController implements the CRUD actions for Video model.
 */
class VideoController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::class,
                    'rules' => [
                        [
                            'allow' => true,
                            'actions' => ['index'],
                            'roles' => ['manageVideo'],
                        ],
                        [
                            'allow' => true,
                            'actions' => ['view'],
                            'roles' => ['viewVideo'],
                        ],
                        [
                            'allow' => true,
                            'actions' => ['create'],
                            'roles' => ['createVideo'],
                        ],
                        [
                            'allow' => true,
                            'actions' => ['update'],
                            'roles' => ['updateVideo'],
                        ],
                        [
                            'allow' => true,
                            'actions' => ['delete'],
                            'roles' => ['deleteVideo'],
                        ],
                    ]
                ],
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Video models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Video::find()->creator(Yii::$app->user->id),
            
            // 'pagination' => [
            //     'pageSize' => 50
            // ],
            'sort' => [
                'defaultOrder' => [
                    'video_id' => SORT_DESC,
                ]
            ],
            
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Video model.
     * @param string $video_id Video ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Video model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Video();

        $model->video = UploadedFile::getInstanceByName('video');

        if ($this->request->isPost) {
            if (Yii::$app->request->isPost && $model->save()) {
                return $this->redirect(['update', 'id' => $model->video_id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Video model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $video_id Video ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $model->thumbnail = UploadedFile::getInstanceByName('thumbnail');

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->video_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Video model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $video_id Video ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Video model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $video_id Video ID
     * @return Video the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Video::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/ChannelController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\User;
use yii\web\Controller;
use common\models\Subscriber;
use common\models\Video;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

class ChannelController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['subscribe'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    public function actionView($username)
    {
        $channel = $this->findChannel($username);

        $dataProvider = new ActiveDataProvider([
            'query' => Video::find()->creator($channel->id)->published()
        ]);

        return $this->render('view',[
            'channel' => $channel,
            'dataProvider' => $dataProvider,
        ]);

    }

    protected function findChannel($username)
    {
        $channel = User::findByUsername($username);
    
        if(!$channel){
            throw new NotFoundHttpException('Channel does not exists');
        }

        return $channel;
    }

    public function actionSubscribe($username)
    {
        $channel = $this->findChannel($username);

        $userId = Yii::$app->user->id;
        $subscriber = $channel->isSubscribed($userId);

        if(!$subscriber){
            $subscriber = new Subscriber();
            $subscriber->channel_id = $channel->id;
            $subscriber->user_id = $userId;
            $subscriber->created_at = time();
            $subscriber->save();
            Yii::$app->mailer->compose([
                    'html' => 'subscriber-html',
                    'text' => 'subscriber-text'
                ],[
                    'channel' => $channel,
                    'user' => Yii::$app->user->identity
                ])->setFrom(Yii::$app->params['senderEmail'])
                ->setTo($channel->email)
                ->setSubject('New subscriber')
                ->send();


        } else{
            $subscriber->delete();
        }

        return $this->renderAjax('_subscribe', [
            'channel' => $channel
        ]);
    }
}

frontend/controllers/CommentsController.php
<?php

namespace frontend\controllers;

use yii\web\Controller;
use common\models\Comment;
use yii\filters\AccessControl;

class CommentsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    public function actionCreate()
    {
        $model = new Comment;

        if ($model->load($this->request->post(), '') && $model->save()) {
            return $this->renderPartial('@frontend/views/video/_comment_item', [
                'model' => $model
            ]);
        }
        
    }
}

frontend/controllers/VideoController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Video;
use common\models\Comment;
use yii\filters\VerbFilter;
use common\models\VideoLike;
use common\models\VideoView;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

class VideoController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['like', 'dislike'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'verb' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'like' => ['post'],
                    'dislike' => ['post'],
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Video::find()->with('createdBy')->with('views')->published()->latest(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionView($id)
    {
        $this->layout = 'blank';
        $video = $this->findVideo($id);

        $videoView = new VideoView();
        $videoView->video_id = $id;
        $videoView->user_id = Yii::$app->user->id;
        $videoView->created_at = time();
        $videoView->save();

        // $similarVideos = Video::find()
        //     ->andWhere('NOT', ['video_id' => $id])
        //     ->published()
        //     ->byKeyword($video->title)
        //     ->limit(10)
        //     ->all();

        $comments = Comment::find()
            ->with(['createdBy'])
            ->videoId($id)
            ->latest()
            ->all();

        return $this->render('view', [
            'model' => $video,
            'comments' => $comments
            // 'similarVideos' => $similarVideos
        ]);

    }

    public function actionHistory()
    {
        $query = Video::find()
                ->alias('v')
                ->innerJoin("(SELECT video_id, MAX(created_at) as max_date FROM video_view 
                    WHERE user_id = :user_id 
                    GROUP BY video_id) vv", 'vv.video_id = v.video_id', [
                        'user_id' => Yii::$app->user->id
                    ])
                ->orderBy('vv.max_date DESC');

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('history', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionLike($id)
    {
        $video = $this->findVideo($id);
        $userId = Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()->userIdVideoId($userId,$id)->one();

        if(!$videoLikeDislike){
           $this->saveLikeDislike($id,$userId,VideoLike::TYPE_LIKE);
        } else if($videoLikeDislike->type === VideoLike::TYPE_LIKE){
            $videoLikeDislike->delete();
        } else{
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id,$userId,VideoLike::TYPE_LIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);

    }

    public function actionDislike($id)
    {
        $video = $this->findVideo($id);
        $userId = Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()->userIdVideoId($userId,$id)->one();

        if(!$videoLikeDislike){
           $this->saveLikeDislike($id,$userId,VideoLike::TYPE_DISLIKE);
        } else if($videoLikeDislike->type === VideoLike::TYPE_DISLIKE){
            $videoLikeDislike->delete();
        } else{
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id,$userId,VideoLike::TYPE_DISLIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);

    }

    protected function saveLikeDislike($videoId, $userId, $type)
    {
        $videoLikeDislike = new VideoLike();
        $videoLikeDislike->video_id = $videoId;
        $videoLikeDislike->user_id = $userId;
        $videoLikeDislike->type = $type;
        $videoLikeDislike->created_at = time();
        $videoLikeDislike->save();
    }

    protected function findVideo($id)
    {
        $video = Video::findOne($id);

        if(!$video){
            throw new NotFoundHttpException("Video does not exists");
        }

        return $video;
    }

    public function actionSearch($keyword = '')
    {
        $query = Video::find()
                // ->select(['video.*', 'score' => "MATCH(title, description, tags) AGAINST ('$keyword')"])
                ->published();
                // ->latest();

        if($keyword){
            $query->byKeyword($keyword);
        }

        $sortColumn = 'created_at';
        $sortType = SORT_DESC;

        $sort = ArrayHelper::getValue($_GET,'sort');

        if($sort){
            
            $sortColumn = $sort;

            if(strpos($sort,'-') === 0){
                $sortColumn = substr($sortColumn,1);
            } else{
                $sortType = SORT_ASC;
            }
            
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => [$sortColumn => $sortType]
            ]
        ]);

        return $this->render('search', [
            'dataProvider' => $dataProvider
        ]);
    }
}

frontend/views/video/_buttons.php
<?php

/**
 * @var $models \common\models\Video
 */

use yii\helpers\Url;

?>
<a data-method="post" data-pjax="1" class="btn btn-sm <?php echo $model->isLikedBy(Yii::$app->user->id) ? 'btn-outline-primary' : 'btn-outline-secondary' ?>" href="<?php echo Url::to(['/video/like', 'id' => $model->video_id]) ?>">
    <i class="fas fa-thumbs-up"></i> <?php echo $model->getLikes()->count() ?>
</a>
<a data-method="post" data-pjax="1" class="btn btn-sm <?php echo $model->isDislikedBy(Yii::$app->user->id) ? 'btn-outline-primary' : 'btn-outline-secondary' ?>" href="<?php echo Url::to(['/video/dislike', 'id' => $model->video_id]) ?>">
    <i class="fas fa-thumbs-down"></i> <?php echo $model->getDislikes()->count() ?>
</a>

frontend/views/video/_comment_item.php
<?php

?>

<div class="media mb-3">
    <img src="https://dummyimage.com/90/ffffff/000000" class="mr-3 comment-avatar" alt="...">
    <div class="media-body">
        <h6 class="mt-0">
            <a class="text-dark" href="#"><?php echo $model->createdBy->username ?></a>
            <small class="text-muted"><?php echo Yii::$app->formatter->asRelativeTime($model->created_at) ?></small>
        </h6>
        <p><?php echo $model->comment ?></p>
    </div>
</div>

frontend/views/video/_video_item.php
<?php

/**
 * @var $model \common\models\Video
 */

use yii\helpers\Url;

?>
<div class="card m-3 video-item">
    <a href="<?php echo Url::to(['/video/view', 'id' => $model->video_id]) ?>">
        <div class="embed-responsive embed-responsive-16by9">
          <img src="<?php echo $model->getThumbnailLink() ?>" class="embed-responsive-item" alt=""> 
        </div>
    </a>
    
  <div class="card-body p-2">
    <h6 class="card-title m-0"><?php echo ucfirst($model->title) ?></h6>
    <p class="text-muted card-text m-0">
      <a href="<?php echo Url::to(['/channel/view', 'username' => $model->createdBy->username ]) ?>"  class="channel-link">
          <?php echo $model->createdBy->username ?>
      </a>
    </p>
    <p class="text-muted card-text m-0"><?php echo $model->getViews()->count() ?> views · <?php echo Yii::$app->formatter->asRelativeTime($model->created_at) ?></p>
  </div>
</div>

frontend/views/video/history.php
<?php
/**
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use yii\widgets\ListView;

?>

<h1>History</h1>

<?php echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/index.php
<?php
/**
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use yii\widgets\ListView;

?>
<?php echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/search.php
<?php
/**
 * @var $dataProvider \yii\data\ActiveDataProvider
 */

use yii\helpers\Url;
use yii\bootstrap4\Html;
use yii\widgets\ListView;
use yii\bootstrap4\Dropdown;
use yii\helpers\ArrayHelper;

$sort = ArrayHelper::getValue($_GET,'sort');
$keyword = ArrayHelper::getValue($_GET,'keyword');

?>

<h1>Results</h1>

<?php echo Html::beginForm(
    Url::to(['video/search']),
    'get'
) ?>
<?php echo Html::hiddenInput('keyword',$keyword) ?>
<?php echo Html::dropDownList(
    'sort', 
    $sort, 
    [
        '' => '',
        'title' => 'Title ASC',
        '-title' => 'Title DESC',
    ], 
    ['onchange'=>'this.form.submit()']
) ?>
<?php echo Html::endForm() ?>


<?php echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/view.php
<?php

/**
 * @var $model common\models\Video
 * @var $comments common\models\Comment
 */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\Pjax;
use common\widgets\SimilarVideos;

?>

 <div class="row">
     <div class="col-sm-8">
        <div class="embed-responsive embed-responsive-16by9">
            <video class="embed-responsive-item" 
                src="<?php echo $model->getVideoLink() ?>" 
                allowfullscreen
                poster="<?php echo $model->getThumbnailLink() ?>"
                controls>
            </video>
        </div>
        <h6 class="mt-2"><?php echo Html::encode($model->title) ?></h6>
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <?php echo $model->getViews()->count() ?> views · <?php echo Yii::$app->formatter->asDate($model->created_at) ?>
            </div>
            <div>
                <?php Pjax::begin() ?>
                    <?php echo $this->render('_buttons',[
                        'model' => $model
                    ]) ?>
                <?php Pjax::end() ?>
            </div>
        </div>
        <div>
            <p>
                <a href="<?php echo Url::to(['/channel/view', 'username' => $model->createdBy->username ]) ?>" class="channel-link">
                    <?php echo $model->createdBy->username ?>
                </a>
            </p>
            <p>
                <?php echo Html::encode($model->description) ?>
            </p>
        </div>
        <div class="comments mt-4">
            <div class="create-comment mb-3">
                <div class="media">
                    <img src="https://dummyimage.com/90/ffffff/000000" class="mr-3 comment-avatar" alt="...">
                    <div class="media-body">
                        <form id="create-comment-form" action="<?php echo Url::to(['/comments/create']) ?>" method="post">
                            <input type="hidden" name="video_id" value="<?php echo $model->video_id ?>">
                            <textarea id="leave-comment" name="comment" id="" rows="1" class="form-control" placeholder="Add a public comment"></textarea>
                            <div class="comment-buttons text-right mt-2">
                                <button type="button" id="cancel-comment" class="btn btn-light">Cancel</button>
                                <button id="submit-comment" class="btn btn-light">Confirm</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div id="comment-wrapper" class="comment-wrapper">
                <?php foreach($comments as $comment){
                    echo $this->render('_comment_item', [
                        'model' => $comment
                    ]);
                } ?>
            </div>
        </div>
     </div>
     <div class="col-sm-4">
        <?= SimilarVideos::widget(['keyword' => $model->title, 'exclude' => $model->video_id]) ?>
     </div>
 </div>